---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
before_install: "gem install bundler -v '~> 1.17'"
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
